eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
                   
spring:
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/microDb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true








  
