eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
                   
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microDb
    username:  '{cipher}cc66eb0cc40a2ba635dd8292615e13c8c07c2e30df9de084444fb205b8605b4d'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true








  
