eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
                   
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microDb
    username:  '{cipher}6e51f07bb4153fbc6901eaf912bb1b592ac306b1a0316d2e49e402024f5e033a'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true








  
